### PR TITLE
Port for Linux

### PR DESCRIPTION
**Pull request by ghost**
Cause you have to do everthing yourself...

### CODE REVIEW

**Comment by TheRealVira** [comment]
Is this a joke m8? Declining your request...

**Comment by ghost** [comment]
Please elaborate your reasons for declining my contribution 👆

**Comment by ghost** [comment]
#1

**Comment by TheRealVira** [comment]
You know what - I'll reopen it. The main reason why I closed it was/is because of the incompletion. You may not know, but the task is to not only download the JRE. The task is to download booth, the JRE and the JDK, setting the specific variables, so your system is able to compile java files and the abbility of creating a testrun (which consists of creating a testing file, which should be able to compile and run). I'll assign you to the issue, and if the task is complete, I'll accept your request. ✌

**Comment by TheRealVira** [comment]
Note to myself:
Can't assign people, which aren't contributers... 😆

**Pull request merged**
